# Generated by Django 6.0 on 2026-03-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_question_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='completed',
        ),
    ]
