# Generated by Django 6.0 on 2026-03-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_remove_question_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(default='عام', max_length=120),
        ),
    ]
